# Generated by Django 5.1.1 on 2024-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('text2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Footer Text',
                'verbose_name_plural': 'Footer Text',
            },
        ),
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='header_text')),
            ],
            options={
                'verbose_name': 'Header Text',
                'verbose_name_plural': 'Header Texts',
            },
        ),
        migrations.CreateModel(
            name='LeftBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='left_block')),
                ('title', models.CharField(max_length=255)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_name', models.TextField(blank=True, max_length=255, null=True)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
                ('description3', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'left_block',
                'verbose_name_plural': 'left_block',
            },
        ),
        migrations.CreateModel(
            name='MiniBlock3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
                ('link_name', models.TextField(blank=True, max_length=255, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='mini_block3')),
            ],
            options={
                'verbose_name': 'mini_block3',
                'verbose_name_plural': 'mini_block3',
            },
        ),
        migrations.CreateModel(
            name='MiniBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='mini_blocks')),
            ],
            options={
                'verbose_name': 'mini_block',
                'verbose_name_plural': 'mini_blocks',
            },
        ),
        migrations.CreateModel(
            name='RightBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='right_block')),
            ],
            options={
                'verbose_name': 'right_block',
                'verbose_name_plural': 'right_block',
            },
        ),
    ]
