# Generated by Django 5.1.1 on 2024-09-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_headertext_options_alter_leftblock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='link_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leftblock',
            name='link_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='miniblock3',
            name='link_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
