# Generated by Django 5.1.1 on 2024-09-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_footertext_link_name_alter_leftblock_link_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
                ('email_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_url', models.URLField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_class', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='QuestionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Questions Block',
                'verbose_name_plural': 'Questions Blocks',
            },
        ),
        migrations.CreateModel(
            name='SevenBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='seven-blocks')),
            ],
            options={
                'verbose_name': 'Seven Blocks',
                'verbose_name_plural': 'Seven Blocks',
            },
        ),
        migrations.CreateModel(
            name='SixBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, max_length=255, null=True)),
                ('html_class', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Six Blocks',
                'verbose_name_plural': 'Six Blocks',
            },
        ),
    ]
