# Generated by Django 5.1.1 on 2024-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_socials'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevenblocks',
            name='link_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sevenblocks',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
