# Generated by Django 5.1.1 on 2024-11-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sevenblocks_link_name_sevenblocks_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sevenblocks',
            name='link_url',
        ),
        migrations.AlterField(
            model_name='sevenblocks',
            name='link_name',
            field=models.TextField(max_length=255),
        ),
    ]
