# Generated by Django 5.1.1 on 2024-11-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_sevenblocks_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevenblocks',
            name='link_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
