# Generated by Django 5.1.1 on 2024-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_sevenblocks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevenblocks',
            name='link_name',
            field=models.TextField(max_length=255),
        ),
    ]
