# Generated by Django 5.1.1 on 2024-11-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sevenblocks_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevenblocks',
            name='image',
            field=models.ImageField(upload_to='seven-blocks'),
        ),
    ]
