# Generated by Django 5.1.1 on 2024-11-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_sevenblocks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevenblocks',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sevenblocks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seven-blocks'),
        ),
        migrations.AlterField(
            model_name='sevenblocks',
            name='link_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
