# Generated by Django 5.1.1 on 2024-11-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_sevenblocks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevenblocks',
            name='link_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
