# Generated by Django 5.1.1 on 2024-11-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_sevenblocks_link_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sevenblocks',
            name='link_name',
        ),
        migrations.AddField(
            model_name='sevenblocks',
            name='text',
            field=models.TextField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='sevenblocks',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
