# Generated by Django 5.1.1 on 2024-11-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_sevenblocks_link_name_sevenblocks_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevenblocks',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sevenblocks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
