# Generated by Django 4.2.13 on 2024-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_sevenblocks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headertext',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='headertext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='header_text'),
        ),
        migrations.AlterField(
            model_name='leftblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='left_block'),
        ),
        migrations.AlterField(
            model_name='miniblock3',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mini-block3'),
        ),
        migrations.AlterField(
            model_name='miniblocks',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='miniblocks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mini-blocks'),
        ),
        migrations.AlterField(
            model_name='questionsblock',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rightblock',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rightblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='right-block'),
        ),
    ]
